config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "download", to: "atendimentos#download"

  root 'home#index'
  resources :atendimentos
  resources :animals
  resources :veterinarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/animal.rb
class Animal < ApplicationRecord
    has_many :atendimentos, :dependent => :destroy
    has_many :veterinarios, through: :atendimentos

    scope :sorted, -> { order(:nome)}

    validates :nome, presence: true, length: {minimum: 3}
    validates :idade, presence: true
    validates :sexo, presence: true, length: {minimum: 1, maximum: 1} 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/atendimento.rb
class Atendimento < ApplicationRecord
  belongs_to :veterinario, :optional => true
  belongs_to :animal, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veterinario.rb
class Veterinario < ApplicationRecord
    has_many :atendimentos, :dependent => :destroy
    has_many :animals, through: :atendimentos

    scope :sorted, -> { order(:nome)}

    validates :nome, presence: true, length: {minimum: 5}
    validates :idade, presence: true, length: {maximum: 2}
    validates :telefone, presence: true, length: {minimum: 9, maximum: 9}
    validates :email, :email_format => { :message => "use o formato identificador@dominio" }
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]


  def index
    current_page = (params[ :page] || 1).to_i
    @animals = Animal.page(current_page).per(2)
  end


  def show
  end


  def new
    @animal = Animal.new
  end


  def edit
  end


  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animals_url(@animal), notice: "Novo animal criado." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: " updated realizado." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Destruição concluida." }
      format.json { head :no_content }
    end
  end

  private

    def set_animal
      @animal = Animal.find(params[:id])
    end


    def animal_params
      params.require(:animal).permit(:nome, :idade, :sexo)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/atendimentos_controller.rb
class AtendimentosController < ApplicationController
  before_action :set_atendimento, only: %i[ show edit update destroy ]

  def download
    @atendimentos= Atendimento.all
    pdf= Prawn::Document.new
    pdf.text "Clínica de animais", :size => 20, :style => :bold
    pdf.move_down 25
    a= 1

    @atendimentos.each do |atendimento|
      pdf.text "atendimento-#{a.to_s}", :size => 20, :style => :bold, :align => :center
      pdf.move_down 5
      pdf.text "Nome do Veterinario: #{atendimento.veterinario.nome}"
      pdf.move_down 5
      pdf.text "Nome do animal: #{atendimento.animal.nome}"
      a=a+1
    end
      send_data(pdf.render,
      filename: "Atendimentos.pdf",
      type:"application/pdf")
end

  def index
    current_page = (params[ :page] || 1).to_i
    @atendimentos = Atendimento.page(current_page).per(2)
  end

  def show
  end


  def new
    @atendimento = Atendimento.new
  end


  def edit
  end


  def create
    @atendimento = Atendimento.new(atendimento_params)

    respond_to do |format|
      if @atendimento.save
        format.html { redirect_to atendimentos_url(@atendimento), notice: "Novo atendimento criado." }
        format.json { render :show, status: :created, location: @atendimento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @atendimento.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @atendimento.update(atendimento_params)
        format.html { redirect_to atendimento_url(@atendimento), notice: " updated realizado." }
        format.json { render :show, status: :ok, location: @atendimento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @atendimento.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @atendimento.destroy

    respond_to do |format|
      format.html { redirect_to atendimentos_url, notice: "destruição concluida." }
      format.json { head :no_content }
    end
  end

  private

    def set_atendimento
      @atendimento = Atendimento.find(params[:id])
    end


    def atendimento_params
      params.require(:atendimento).permit(:atendimentos_data, :veterinario_id, :animal_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/veterinarios_controller.rb
class VeterinariosController < ApplicationController
  before_action :set_veterinario, only: %i[ show edit update destroy ]


  def index
    current_page = (params[ :page] || 1).to_i
    @veterinarios = Veterinario.page(current_page).per(2)
  end


  def show
  end


  def new
    @veterinario = Veterinario.new
  end


  def edit
  end


  def create
    @veterinario = Veterinario.new(veterinario_params)

    respond_to do |format|
      if @veterinario.save
        format.html { redirect_to veterinarios_url(@veterinario), notice: "Novo veterinario criado." }
        format.json { render :show, status: :created, location: @veterinario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @veterinario.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @veterinario.update(veterinario_params)
        format.html { redirect_to veterinario_url(@veterinario), notice: " updated realizado." }
        format.json { render :show, status: :ok, location: @veterinario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @veterinario.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @veterinario.destroy

    respond_to do |format|
      format.html { redirect_to veterinarios_url, alert: "destruição concluida." }
      format.json { head :no_content }
    end
  end

  private
 
    def set_veterinario
      @veterinario = Veterinario.find(params[:id])
    end


    def veterinario_params
      params.require(:veterinario).permit(:nome, :idade, :telefone, :email)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/veterinarios_helper.rb
module VeterinariosHelper
end

app/views/animals/_animal.html.erb
<table class="table" style="background-color:#e2f3f5">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nome</th>
      <th scope="col">idade</th>
      <th scope="col">sexo</th>
      <th scope="col">opções</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= animal.id %></th>
      <td><%= animal.nome %></td>
      <td><%= animal.idade %></td>
      <td><%= animal.sexo %></td>
      <td>
        <a href="<%= edit_animal_path(animal)%>" class="text-decoration-none">
          <button type="button" class="btn btn-outline-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard2" viewBox="0 0 16 16">
              <path d="M3.5 2a.5.5 0 0 0-.5.5v12a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-12a.5.5 0 0 0-.5-.5H12a.5.5 0 0 1 0-1h.5A1.5 1.5 0 0 1 14 2.5v12a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-12A1.5 1.5 0 0 1 3.5 1H4a.5.5 0 0 1 0 1h-.5Z"/>
              <path d="M10 .5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5.5.5 0 0 1-.5.5.5.5 0 0 0-.5.5V2a.5.5 0 0 0 .5.5h5A.5.5 0 0 0 11 2v-.5a.5.5 0 0 0-.5-.5.5.5 0 0 1-.5-.5Z"/>
            </svg>
          </button>
        </a>
        <a href="<%= animal_path(animal)%>" class="text-decoration-none">
          <button type="button" class="btn btn-outline-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-display" viewBox="0 0 16 16">
              <path d="M0 4s0-2 2-2h12s2 0 2 2v6s0 2-2 2h-4c0 .667.083 1.167.25 1.5H11a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1h.75c.167-.333.25-.833.25-1.5H2s-2 0-2-2V4zm1.398-.855a.758.758 0 0 0-.254.302A1.46 1.46 0 0 0 1 4.01V10c0 .325.078.502.145.602.07.105.17.188.302.254a1.464 1.464 0 0 0 .538.143L2.01 11H14c.325 0 .502-.078.602-.145a.758.758 0 0 0 .254-.302 1.464 1.464 0 0 0 .143-.538L15 9.99V4c0-.325-.078-.502-.145-.602a.757.757 0 0 0-.302-.254A1.46 1.46 0 0 0 13.99 3H2c-.325 0-.502.078-.602.145z"/>
            </svg>
          </svg>
        </button>
      </tr>
    </tbody>
  </table>

app/views/animals/_form.html.erb
<%= simple_form_for animal do |form| %>
  <%= form.error_notification%>
  <%= form.error_notification message: form.object.erros[:base].to_sentence if form.object.errors[:base].present? %>

    <%= form.input :nome, style: "display: block"  %>
    <%= form.input :idade, style: "display: block"  %>
    <%= form.input :sexo, style: "display: block"  %>

  <div style="padding: 20px">
    <%= form.button :submit, class: "btn btn-success" %>
    <%= link_to "voltar para animais", animals_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/animals/_pagination.html.erb
<div class="site_pagination" aria-label="pagination">

    <%= link_to_previous_page @animals, "<", class: "btn btn-outline-primary"%>
    <%= link_to_next_page @animals, ">", class: "btn btn-outline-primary"%>
    
</div>

app/views/animals/edit.html.erb
<h1>Editing animal</h1>

<%= render "form", animal: @animal %>

<br>

app/views/animals/index.html.erb
<h1>Animais</h1>

<div id="animals">
  <ul>
    <% @animals.each do |animal| %>
      <p>  
        <li>
          <%= render animal %>
        </li>
      </p>
    <% end %>
  <%= render "pagination" %>
  </div>
    <ul>
      <%= link_to "Novo animal", new_animal_path, class: "btn btn-primary" %>
    </ul>
  </ul>

app/views/animals/new.html.erb
<h1>New animal</h1>

<%= render "form", animal: @animal %>

<br>

app/views/animals/show.html.erb
<%= render @animal %>

<div>
  <%= link_to "Voltar para animais", animals_path, class: "btn btn-secondary" %>

  <%= button_to "Apagar esse animal", @animal, method: :delete, class: "btn btn-danger" %>
</div>

app/views/atendimentos/_atendimento.html.erb
<table class="table" style="background-color:#e2f3f5">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">data</th>
      <th scope="col">veterinario</th>
      <th scope="col">animal</th>
      <th scope="col">opções</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= atendimento.id %></th>
      <td><%= atendimento.atendimentos_data %></td>
      <td><%= atendimento.veterinario.nome %></td>
      <td><%= atendimento.animal.nome %></td>
      <td>
        <a href="<%= edit_atendimento_path(atendimento)%>" class="text-decoration-none">
          <button type="button" class="btn btn-outline-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard2" viewBox="0 0 16 16">
              <path d="M3.5 2a.5.5 0 0 0-.5.5v12a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-12a.5.5 0 0 0-.5-.5H12a.5.5 0 0 1 0-1h.5A1.5 1.5 0 0 1 14 2.5v12a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-12A1.5 1.5 0 0 1 3.5 1H4a.5.5 0 0 1 0 1h-.5Z"/>
              <path d="M10 .5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5.5.5 0 0 1-.5.5.5.5 0 0 0-.5.5V2a.5.5 0 0 0 .5.5h5A.5.5 0 0 0 11 2v-.5a.5.5 0 0 0-.5-.5.5.5 0 0 1-.5-.5Z"/>
            </svg>
          </button>
        </a>
        <a href="<%= atendimento_path(atendimento)%>" class="text-decoration-none">
          <button type="button" class="btn btn-outline-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-display" viewBox="0 0 16 16">
              <path d="M0 4s0-2 2-2h12s2 0 2 2v6s0 2-2 2h-4c0 .667.083 1.167.25 1.5H11a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1h.75c.167-.333.25-.833.25-1.5H2s-2 0-2-2V4zm1.398-.855a.758.758 0 0 0-.254.302A1.46 1.46 0 0 0 1 4.01V10c0 .325.078.502.145.602.07.105.17.188.302.254a1.464 1.464 0 0 0 .538.143L2.01 11H14c.325 0 .502-.078.602-.145a.758.758 0 0 0 .254-.302 1.464 1.464 0 0 0 .143-.538L15 9.99V4c0-.325-.078-.502-.145-.602a.757.757 0 0 0-.302-.254A1.46 1.46 0 0 0 13.99 3H2c-.325 0-.502.078-.602.145z"/>
            </svg>
          </svg>
        </button>
      </tr>
    </tbody>
  </table>

app/views/atendimentos/_form.html.erb
<%= simple_form_for(@atendimento) do |f| %>
  <%= f.error_notification%>
  <%= f.error_notification message: f.object.erros[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="f-inputs">
    <%= f.input :atendimentos_data, style: "display: block" %>
    <%= f.association :veterinario, collection: Veterinario.all ,style: "display: block" %>
    <%= f.association :animal, collection: Animal.sorted ,style: "display: block" %>
  </div>

  <div class="f-inputs" style="padding: 20px">
    <%= f.button :submit, class: "btn btn-success" %>
    <%= link_to "voltar para atendimentos", atendimentos_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/atendimentos/_pagination.html.erb
<div class="site_pagination" aria-label="pagination">

    <%= link_to_previous_page @atendimentos, "<", class: "btn btn-outline-primary"%>
    <%= link_to_next_page @atendimentos, ">", class: "btn btn-outline-primary"%>
    
</div>

app/views/atendimentos/edit.html.erb
<h1>Editing atendimento</h1>
<div>

<%= render "form", atendimento: @atendimento %>

</div>

app/views/atendimentos/index.html.erb
<h1>Atendimentos</h1>
<div id="atendimentos">
  <% @atendimentos.each do |atendimento| %>
    <%= render atendimento %>
  <% end %>
  <%= render "pagination" %>
</div>
<ul style="padding:10px">
  <%= link_to "Novo atendimento", new_atendimento_path, class: "btn btn-primary" %>
  <%= link_to atendimentos_path(format: :csv), class:"btn btn-success" do %>
    <span>Baixar CSV </span>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-filetype-csv" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5L14 4.5ZM3.517 14.841a1.13 1.13 0 0 0 .401.823c.13.108.289.192.478.252.19.061.411.091.665.091.338 0 .624-.053.859-.158.236-.105.416-.252.539-.44.125-.189.187-.408.187-.656 0-.224-.045-.41-.134-.56a1.001 1.001 0 0 0-.375-.357 2.027 2.027 0 0 0-.566-.21l-.621-.144a.97.97 0 0 1-.404-.176.37.37 0 0 1-.144-.299c0-.156.062-.284.185-.384.125-.101.296-.152.512-.152.143 0 .266.023.37.068a.624.624 0 0 1 .246.181.56.56 0 0 1 .12.258h.75a1.092 1.092 0 0 0-.2-.566 1.21 1.21 0 0 0-.5-.41 1.813 1.813 0 0 0-.78-.152c-.293 0-.551.05-.776.15-.225.099-.4.24-.527.421-.127.182-.19.395-.19.639 0 .201.04.376.122.524.082.149.2.27.352.367.152.095.332.167.539.213l.618.144c.207.049.361.113.463.193a.387.387 0 0 1 .152.326.505.505 0 0 1-.085.29.559.559 0 0 1-.255.193c-.111.047-.249.07-.413.07-.117 0-.223-.013-.32-.04a.838.838 0 0 1-.248-.115.578.578 0 0 1-.255-.384h-.765ZM.806 13.693c0-.248.034-.46.102-.633a.868.868 0 0 1 .302-.399.814.814 0 0 1 .475-.137c.15 0 .283.032.398.097a.7.7 0 0 1 .272.26.85.85 0 0 1 .12.381h.765v-.072a1.33 1.33 0 0 0-.466-.964 1.441 1.441 0 0 0-.489-.272 1.838 1.838 0 0 0-.606-.097c-.356 0-.66.074-.911.223-.25.148-.44.359-.572.632-.13.274-.196.6-.196.979v.498c0 .379.064.704.193.976.131.271.322.48.572.626.25.145.554.217.914.217.293 0 .554-.055.785-.164.23-.11.414-.26.55-.454a1.27 1.27 0 0 0 .226-.674v-.076h-.764a.799.799 0 0 1-.118.363.7.7 0 0 1-.272.25.874.874 0 0 1-.401.087.845.845 0 0 1-.478-.132.833.833 0 0 1-.299-.392 1.699 1.699 0 0 1-.102-.627v-.495Zm8.239 2.238h-.953l-1.338-3.999h.917l.896 3.138h.038l.888-3.138h.879l-1.327 4Z"/>
    </svg>
    <%= link_to download_path, class:"btn btn-success" do %>
      <span >Baixar PDF </span>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-filetype-pdf" viewBox="0 0 16 16" >
        <path fill-rule="evenodd" d="M14 4.5V14a2 2 0 0 1-2 2h-1v-1h1a1 1 0 0 0 1-1V4.5h-2A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v9H2V2a2 2 0 0 1 2-2h5.5L14 4.5ZM1.6 11.85H0v3.999h.791v-1.342h.803c.287 0 .531-.057.732-.173.203-.117.358-.275.463-.474a1.42 1.42 0 0 0 .161-.677c0-.25-.053-.476-.158-.677a1.176 1.176 0 0 0-.46-.477c-.2-.12-.443-.179-.732-.179Zm.545 1.333a.795.795 0 0 1-.085.38.574.574 0 0 1-.238.241.794.794 0 0 1-.375.082H.788V12.48h.66c.218 0 .389.06.512.181.123.122.185.296.185.522Zm1.217-1.333v3.999h1.46c.401 0 .734-.08.998-.237a1.45 1.45 0 0 0 .595-.689c.13-.3.196-.662.196-1.084 0-.42-.065-.778-.196-1.075a1.426 1.426 0 0 0-.589-.68c-.264-.156-.599-.234-1.005-.234H3.362Zm.791.645h.563c.248 0 .45.05.609.152a.89.89 0 0 1 .354.454c.079.201.118.452.118.753a2.3 2.3 0 0 1-.068.592 1.14 1.14 0 0 1-.196.422.8.8 0 0 1-.334.252 1.298 1.298 0 0 1-.483.082h-.563v-2.707Zm3.743 1.763v1.591h-.79V11.85h2.548v.653H7.896v1.117h1.606v.638H7.896Z"/>
      </svg>
    <% end %>
  <% end %>
</ul>

app/views/atendimentos/new.html.erb
<h1>Novo atendimento</h1>

<%= render "form", atendimento: @atendimento %>

<br>

app/views/atendimentos/show.html.erb
<%= render @atendimento %>

<div style="padding:5px">
 <span><%= link_to "Voltar para atendimentos", atendimentos_path, class: "btn btn-secondary" %></span>
 <span><%= button_to "Apagar esse atendimento", @atendimento, method: :delete, class: "btn btn-danger" %></span>
</div>

app/views/layouts/_simple_header.html.erb
  <div class="container" style="background-color:#c5e3f6;margin:5px;border-radius:1%" >
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto ">
       <img src="C:\browch\vscode\RAILS\Trabalho_Final\Pet\app\assets\images\cruz-médica-com-pata-do-s-cão-113031160.jpg" class="img-thumbnail" alt="logo cruz com patinha" style="color:black;width:50px;height:50px">
      </a>
      

    <ul class="nav nav-pills"  >
        <li class="nav-item"><a href="<%=veterinarios_path%>" style="background-color:#e2f3f5;color:black;margin:5px;border-radius:50%" class="nav-link">Veterinarios</a></li>
        <li class="nav-item"><a href="<%=animals_path%>" style="background-color:#e2f3f5;color:black;margin:5px;border-radius:50%" class="nav-link">Animais</a></li>
        <li class="nav-item"><a href="<%=atendimentos_path%>" style="background-color:#e2f3f5;color:black;margin:5px;border-radius:50%" class="nav-link">Atendimentos</a></li>
        <li class="nav-item"><a href="#" style="background-color:#e2f3f5;color:black;margin:5px;border-radius:50%" class="nav-link">About</a></li>
      </ul>
    </header>
  </div>

app/views/veterinarios/_form.html.erb
<%= simple_form_for veterinario do |form| %>
  <%= form.error_notification%>
  <%= form.error_notification message: form.object.erros[:base].to_sentence if form.object.errors[:base].present? %>

  <div>
    <%= form.input :nome, style: "display: block" %>
    <%= form.input :idade, style: "display: block" %>
    <%= form.input :telefone, style: "display: block" %>
    <%= form.input :email, style: "display: block" %>
  </div>

  <div style="padding: 20px">
    <%= form.button :submit, class: "btn btn-success"%>
    <%= link_to "voltar para veterinarios", veterinarios_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/veterinarios/_veterinario.html.erb
<table class="table" style="background-color:#e2f3f5">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Nome</th>
      <th scope="col">idade</th>
      <th scope="col">telefone</th>
      <th scope="col">email</th>
      <th scope="col">opções</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= veterinario.id %></th>
      <td><%= veterinario.nome %></td>
      <td><%= veterinario.idade %></td>
      <td><%= veterinario.telefone %></td>
      <td><%= veterinario.email %></td>
      <td>
        <a href="<%= edit_veterinario_path(veterinario)%>" class="text-decoration-none">
          <button type="button" class="btn btn-outline-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard2" viewBox="0 0 16 16">
              <path d="M3.5 2a.5.5 0 0 0-.5.5v12a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5v-12a.5.5 0 0 0-.5-.5H12a.5.5 0 0 1 0-1h.5A1.5 1.5 0 0 1 14 2.5v12a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 14.5v-12A1.5 1.5 0 0 1 3.5 1H4a.5.5 0 0 1 0 1h-.5Z"/>
              <path d="M10 .5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5.5.5 0 0 1-.5.5.5.5 0 0 0-.5.5V2a.5.5 0 0 0 .5.5h5A.5.5 0 0 0 11 2v-.5a.5.5 0 0 0-.5-.5.5.5 0 0 1-.5-.5Z"/>
            </svg>
          </button>
        </a>
        <a href="<%= veterinario_path(veterinario)%>" class="text-decoration-none">
          <button type="button" class="btn btn-outline-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-display" viewBox="0 0 16 16">
              <path d="M0 4s0-2 2-2h12s2 0 2 2v6s0 2-2 2h-4c0 .667.083 1.167.25 1.5H11a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1h.75c.167-.333.25-.833.25-1.5H2s-2 0-2-2V4zm1.398-.855a.758.758 0 0 0-.254.302A1.46 1.46 0 0 0 1 4.01V10c0 .325.078.502.145.602.07.105.17.188.302.254a1.464 1.464 0 0 0 .538.143L2.01 11H14c.325 0 .502-.078.602-.145a.758.758 0 0 0 .254-.302 1.464 1.464 0 0 0 .143-.538L15 9.99V4c0-.325-.078-.502-.145-.602a.757.757 0 0 0-.302-.254A1.46 1.46 0 0 0 13.99 3H2c-.325 0-.502.078-.602.145z"/>
            </svg>
          </svg>
        </button>
      </tr>
    </tbody>
  </table>

app/views/veterinarios/index.html.erb
<h1>Veterinarios</h1>

<div id="veterinarios">
  <ul>
    <% @veterinarios.each do |veterinario| %>
        <p>
          <li>
            <%= render veterinario %>
          </li>
        <p>
    <% end %>
  <%= render "pagination"%>
  </div>
    <ul>
      <%= link_to "Novo veterinario", new_veterinario_path, class: "btn btn-primary" %>
      <%= link_to veterinarios_path(format: :csv), class:"btn btn-success" do %>
            <span>Baixar CSV </span>

   <% end %>
    </ul>
  </ul>

app/views/veterinarios/show.html.erb
<%= render @veterinario %>

<div>
  <%= link_to "Voltar para veterinarios", veterinarios_path, class: "btn btn-secondary" %>
  <%= button_to "Apagar esse veterinario", @veterinario, method: :delete, class: "btn btn-danger"%>
</div>